### ISSUE TITLE
Cannot set userId when registering for push notifications

### ISSUE THREAD

**Issue by gferreri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#1]
The Push Notification REST API supports sending notifications to a specific userId, but there doesn't seem to be a way to set the userId that is passed to the Push Notification Service. In fact, in BMSPushClient.swift, it appears to be hardcoded to an empty string. There is some commented-out code that appears to be an initial attempt at supporting a consumerId. What's the plan for supporting this in the future?

**Comment by AnanthaKrish** [comment]
Hi, We are not supporting UserId based notifications right now.

**Comment by wonderMan-codes** [comment]
Are you guys supporting it now? I was thinking I could set the UID as the topic?

**Comment by AnanthaKrish** [comment]
@wonderMan-codes Hi, yes its available - https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-push#register-for-notifications

**Comment by wonderMan-codes** [comment]
@AnanthaKrish, great. can you help me with this: https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-push/issues/106
