### ISSUE TITLE
The unregister Notification function should change from unRegisterDevice to unregisterDevice

### ISSUE THREAD

**Issue by xiangmin2587** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#100]
![unregister](https://user-images.githubusercontent.com/2128833/82146493-59042800-987d-11ea-84c1-41a453d7abf8.jpg)
![unregisterError](https://user-images.githubusercontent.com/2128833/82146515-79cc7d80-987d-11ea-8cc1-ccb391a165fe.jpg)

**Comment by AnanthaKrish** [comment]
@xiangmin2587 Please use `react-native push` plugin version 1.3.2.

**Comment by xiangmin2587** [comment]
@AnanthaKrish   sorry I am not quite understand your mean, do you mean use another lib?  can  you let me the steps to apply the plugin version 1.3.2?

**Comment by AnanthaKrish** [comment]
@xiangmin2587 We have released a new version of the `bmd-push-react-native` plugin. Version which contains the fix is 1.3.2. You can use that.
