### ISSUE TITLE
Dependency BMSCore does not compile with XCode 8 GM

### ISSUE THREAD

**Issue by slizeray** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#17]
Showing All Messages
/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/BaseRequest.swift:327:17: Instance method 'urlSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' nearly matches optional requirement 'urlSession(_:task:willPerformHTTPRedirection:newRequest:completionHandler:)' of protocol 'URLSessionTaskDelegate'

/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/BaseRequest.swift:255:52: Cannot convert value of type 'Error?' to expected argument type 'NSError?'

/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/BaseRequest.swift:274:23: 'init' has been renamed to 'init(describing:)'

/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/BaseRequest.swift:335:65: 'init' has been renamed to 'init(describing:)'

/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/Request.swift:56:28: error: cannot assign value of type 'Data?' to type 'NSData?'
        savedRequestBody = requestBody
                           ^~~~~~~~~~~
                                       as NSData?

/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/Response.swift:66:38: error: cannot assign value of type '[AnyHashable : Any]?' to type '[NSObject : AnyObject]?'
        self.headers = httpResponse?.allHeaderFields
                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
                                                     as [NSObject : AnyObject]?
/Users/slizeray/Devel/Pulsar/Pods/BMSCore/Source/Network Requests/Response.swift:69:29: error: cannot assign value of type 'Data?' to type 'NSData?'
        self.responseData = responseData
                            ^~~~~~~~~~~~
                                         as NSData?

**Comment by AnanthaKrish** [comment]
Swift 3 support is added.

**Comment by slizeray** [comment]
Thanks, but it would be great if you could use Swift 3.0 overflow data types in the function definitions such as : 
        public func registerWithDeviceToken(deviceToken:NSData , WithUserId:String?, completionHandler: @escaping(_ response:String?, _ statusCode:Int?, _ error:String) -> Void) {

The device token should be of type Data instead of NSData. The deviceToken passed by iOS in the app delegate is of type Data and not NSData.

Thanks!
