### ISSUE TITLE
initializeWithAppGUID parameters are optional, but error when not present

### ISSUE THREAD

**Issue by tfrank64** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#24]
This confused me for awhile, because I used to be able to call `initializeWithAppGUID` with just the  `appGUID`. So the other day I was calling it with the a nil `clientSecret` and it continually caused my application to crash due to a force unwrap [here](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-push/blob/master/Source/BMSPushClient.swift#L97). I suggest we make these parameters non-optional to avoid this issue.

Additionally, the README still contains examples of `push.initializeWithAppGUID(appGUID: "your push App GUID")` when I believe that is a deprecated method, correct?

**Comment by tfrank64** [comment]
Any updates on this or has it been looked at yet?

**Comment by AnanthaKrish** [comment]
Solved it... Will release the SDK soon..
