### ISSUE TITLE
libraries BMScore not identified in xcode

### ISSUE THREAD

**Issue by vasuvuggu** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#36]
No such module BMSCore in xcode points to,
& even
#import  "TestProject-Swift.h" not identified,
in appDelegate.m files
CDVBMSPush  not identified in the same appDeletegate.m files.

**Comment by AnthonyOliveri** [comment]
It sounds like you are using Cordova for your Bluemix Mobile Services app. Could you please move this issue to the [Cordova repository](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-cordova-plugin-push), and add details on the steps you took that led you to this issue?

**Comment by vasuvuggu** [comment]
thanks i wl do
