### ISSUE TITLE
Crash in BMSPushClient.swift:665

### ISSUE THREAD

**Issue by meyumeapps** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#41]
Hi,

We've just started using Bluemix Push in our app and have picked up a couple of crashes in Crashlytics .
If you can give us any pointers that would be great please.
Thanks
Scott

Using BMSAnalyticsAPI (2.2.0)
Using BMSCore (2.3.1)
Using BMSPush (3.1.1)

[BMSPush-Crash-1.txt](https://github.com/ibm-bluemix-mobile-services/bms-clientsdk-swift-push/files/874697/BMSPush-Crash-1.txt)

**Comment by AnanthaKrish** [comment]
Issue is solved , hence closing the defect
