### ISSUE TITLE
Error while building the pod with Swift 4

### ISSUE THREAD

**Issue by rajishere** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#74]
Hi @AnanthaKrish 

We are facing an error `'subtractWithOverflow' is unavailable: Use subtractingReportingOverflow(_:) instead.'` in `RequestMetadata > combinedMetadata > line 61`, when building with Swift 4.0. For now we are using 3.2 as a work around. Please verify if this needs a fix

**Comment by AnanthaKrish** [comment]
@rajishere This is not a push sdk issue ...Its BMSAnalyticsAPI issue. I will try to solve it ..

**Comment by AnanthaKrish** [comment]
@rajishere I have tried with Xcode 9.2 and swift 4 app, but not able to recreate the issue. Can you tell me how to re create this issue ?

Please check the version also,

```
 BMSAnalyticsAPI (2.2.3)
 BMSCore (2.3.5)
BMSPush (3.2.6)
```
