### ISSUE TITLE
Cannot register the device token to the BMSPushClient 

### ISSUE THREAD

**Issue by Chiu1** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#85]
- Using BMSCore (2.3.5)
- Using BMSPush (3.3.2)
Cannot use the method registerWithDeviceToken in my objective-c base project.

I am trying to migrate the IMFPush to BMSPush but the genearted BMSPushClient-Swift.h are not include the registerWithDeviceToken method. I have tried to decare the function manully but the IDE report the message as below.

```
@objc(registerWithDeviceToken:withUserId:)
public func registerWithDeviceToken (deviceToken:Data, completionHandler: @escaping(_ response:String?, _ statusCode:Int?, _ error:String) -> Void) {
        if (isInitialized){

```
Method cannot be marked @objc because the type of the parameter 2 cannot be represented in Objective-C

Lastly, May i have the migration grade from IMFPush to BMSPush in objectie-C based cordova project.

**Comment by AnanthaKrish** [comment]
@Chiu1 

1. We don't support objective-c.. 
2. are you using the cordova push plugin ? if yes , which version are you using ?

**Comment by Chiu1** [comment]
@AnanthaKrish 
Thanks for your reply, 
On the #1 we are integrating the mobile first SDK into the existing Cordova project. But we find they are using the IMFCore and IMFPush framework. Once we install the mobile first plugin, there will crash and show4 the duplicate class issue on PSecurityUtils, WLUtils etc.
On the #2, IMFCore and IMFPush. Cannot find the version.

**Comment by AnanthaKrish** [comment]
@Chiu1 The IBM Cloud push notifications plugin is `bms-push` and the core plugin is `bms-core`.  IMFCore and IMFPush are no longer supported . For push notifications service, try using the `bms-push` plugin.

**Comment by Chiu1** [comment]
@AnanthaKrish May I know is there have any migration guide from IMFPush to BMS-push in Objective-C based project. And is it  [blog](https://www.ibm.com/blogs/bluemix/2016/12/deprecation-bluemix-mobile-services-objective-c-sdks/) still possible?

**Comment by AnanthaKrish** [comment]
@Chiu1 I will check that and get back to you .
 By the way bms-push supports objective-C. If you are using only push notifications service, please try to remove the old plugin and add the bms-push .

**Comment by Chiu1** [comment]
@AnanthaKrish 
I have solved the issue by creating a custom BMSSDKbridge.swift.
But is that have any logic change within the PushClient, because I follow the existing implementation to migrate the IMF to BMS will cause the infinite loop on didRegisterForRemoteNotificationsWithDeviceToken:.

Here is the code

Production implementation with IMFCore and IMFPush
```
- (void) didFinishLaunchingWithOptions:(NSNotification *)notification {
IMFClient *imfClient = [IMFClient sharedInstance];
[imfClient initializeWithBackendRoute:BLUEMIX_ROUTE backendGUID:BLUEMIX_APP_GUID];
...
}

- (void) didRegisterForRemoteNotificationsWithDeviceToken:(NSNotification *)deviceToken {
...
IMFPushClient *push = [IMFPushClient sharedInstance];
[push initializeWithAppGUID:BLUEMIX_APP_GUID clientSecret:BLUEMIX_CLIENT_SECRET];
[push registerWithDeviceToken:_deviceToken completionHandler:^(IMFResponse *response, NSError *error) {
        ....
    }];
}
```

I have change to this version to prevent the infinite loop
```
- (void) didFinishLaunchingWithOptions:(NSNotification *)notification {
[BMSClientObjc initializeWithBackendRoute:BLUEMIX_ROUTE backendGUID:BLUEMIX_APP_GUID region:BMSClientObjc.REGION_SYDNEY];
[BMSPushClientObjc initializeWithAppGUID:BLUEMIX_APP_GUID clientSecret:BLUEMIX_CLIENT_SECRET];
...
}

- (void) didRegisterForRemoteNotificationsWithDeviceToken:(NSNotification *)deviceToken {
...
[BMSPushClientObjc registerWithDeviceToken:_deviceToken completionHandler:^(NSString * responseJson, NSNumber * statusCode, NSString * error) {
       ...
    }];
}
```

**Comment by AnanthaKrish** [comment]
@Chiu1 There are modifications . BMS SDK will take care of Apple pushnotifications register calls from the iPhone. If you call those methods , definitely it will lead into loops. But it won't be infinite loops. The above one is correct .

**Comment by Chiu1** [comment]
@AnanthaKrish 
Observed a crash when calling register device.
My implementation
```
let push  = BMSPushClient.sharedInstance
        push.initializeWithAppGUID(appGUID: appGUID, clientSecret: clientSecret)
        push.registerWithDeviceToken(deviceToken: deviceToken, completionHandler: { (response, statusCode, error) -> Void in
            if error.isEmpty {
                print("success")
            }else{
                print(error)
            }
        })
```
Crash stack 
#0	0x0000000101980410 in specialized BMSPushUrlBuilder.init(applicationID:clientSecret:) ()
#1	0x000000010196da64 in BMSPushClient.registerWithDeviceToken(deviceToken:completionHandler:) ()
#2	0x0000000100f56054 in static BMSPushClientObjc.registerPushService(appGUID:clientSecret:deviceToken:completionHandler:) at /Users/wingchiuchoi/Documents/IBM/BEA/BEA-App-2018/CCCDI_FULL_SOURCE/platforms/ios/BEA/Plugins/cordova-plugin-bea-notifications/BMSSDKBridge.swift:27
#3	0x0000000100f563c8 in @objc static BMSPushClientObjc.registerPushService(appGUID:clientSecret:deviceToken:completionHandler:) ()
#4	0x0000000100f4bb50 in -[BEANotification didRegisterForRemoteNotificationsWithDeviceToken:] at /Users/wingchiuchoi/Documents/IBM/BEA/BEA-App-2018/CCCDI_FULL_SOURCE/platforms/ios/BEA/Plugins/cordova-plugin-bea-notifications/BEANotification.m:917
#5	0x0000000183d44c3c in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#6	0x0000000183d441b8 in _CFXRegistrationPost ()
#7	0x0000000183d43f14 in ___CFXNotificationPost_block_invoke ()
#8	0x0000000183dc184c in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#9	0x0000000183c7af38 in _CFXNotificationPost ()
#10	0x00000001846ebbbc in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#11	0x0000000100f551e8 in -[AppDelegate(BEAAppEvent) postNotificationName:object:] at /Users/wingchiuchoi/Documents/IBM/BEA/BEA-App-2018/CCCDI_FULL_SOURCE/platforms/ios/BEA/Plugins/cordova-plugin-bea-notifications/AppDelegate+BEAAppEvent.m:143
#12	0x0000000100f54ddc in -[AppDelegate(BEAAppEvent) swizzled_application:didRegisterForRemoteNotificationsWithDeviceToken:] at /Users/wingchiuchoi/Documents/IBM/BEA/BEA-App-2018/CCCDI_FULL_SOURCE/platforms/ios/BEA/Plugins/cordova-plugin-bea-notifications/AppDelegate+BEAAppEvent.m:83
#13	0x00000001024ed260 in _dispatch_call_block_and_release ()
