### ISSUE TITLE
3.4.2 >> error: no such module 'WatchKit'

### ISSUE THREAD

**Issue by PacteraSunChao** [ibm-bluemix-mobile-services/bms-clientsdk-swift-push#93]
`Xcode11 GM Seed 1` && `Swift4.2`

**Comment by PacteraSunChao** [comment]
https://forums.developer.apple.com/thread/122683

**Comment by PacteraSunChao** [comment]
read it , please 👆

**Comment by jojustin** [comment]
@PacteraSunChao We are looking into this.  Will revert back at the earliest.

**Comment by AnanthaKrish** [comment]
@PacteraSunChao Please update to the new version of core SDK - 2.5.0.

**Comment by PacteraSunChao** [comment]
I have been using the new version of push SDK - 3.4.4 and it is OK.
